# Generated by Django 4.2.11 on 2024-04-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ForeignKey(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Товар'),
        ),
    ]
